using dsaproblem.Arrays;
using dsaproblem.ArraysMultiD;
using dsaproblem.Practice;
// using dsaproblem.Recursions;
using dsaproblem.Sorting;
// using dsaproblem.Strings;
using dsaproblem.Striver;
using dsaproblem.Striver.Arrays;
using dsaproblem.Striver.Arrays.Medium;
using dsaproblem.Striver.BasicMaths;
using dsaproblem.Striver.Hashing;
using dsaproblem.Striver.LinkedList;
using dsaproblem.Striver.Strings;
using dsaproblem.Wipro;
using Recursions;
using ReviseExtension;

// PracticeExtension.Practice();
// ArraysExtension.Practice();
// StringExtension.Practice();
// MultiDArraysExtension.Practice();
// SortingExtension.Practice();
// RecursionExtension.Practice();
// BasicMathExtension.Practice();
// HashingExtension.Practice();
// ArrayExtension.Practice();
// WiproExtension.Practice();
// StringExtension.Practice();
// LinkedListExtension.Practice();
// Revise.Practice();
RecursionExtension.Practice();